// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Api struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// this is the request to the api
	Options *Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// these are different responses based on the type of request you make
	Trip       *Trip       `protobuf:"bytes,2,opt,name=trip,proto3" json:"trip,omitempty"`             // trace_attributes
	Directions *Directions `protobuf:"bytes,3,opt,name=directions,proto3" json:"directions,omitempty"` // route, optimized_route, trace_route, centroid
	Status     *Status     `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`         // status
	Matrix     *Matrix     `protobuf:"bytes,5,opt,name=matrix,proto3" json:"matrix,omitempty"`         // sources_to_targets
	Isochrone  *Isochrone  `protobuf:"bytes,6,opt,name=isochrone,proto3" json:"isochrone,omitempty"`   // isochrone
	Expansion  *Expansion  `protobuf:"bytes,7,opt,name=expansion,proto3" json:"expansion,omitempty"`   // expansion
	// here we store a bit of info about what happened during request processing (stats/errors/warnings)
	Info          *Info `protobuf:"bytes,20,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Api) Reset() {
	*x = Api{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api) ProtoMessage() {}

func (x *Api) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api.ProtoReflect.Descriptor instead.
func (*Api) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *Api) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Api) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

func (x *Api) GetDirections() *Directions {
	if x != nil {
		return x.Directions
	}
	return nil
}

func (x *Api) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Api) GetMatrix() *Matrix {
	if x != nil {
		return x.Matrix
	}
	return nil
}

func (x *Api) GetIsochrone() *Isochrone {
	if x != nil {
		return x.Isochrone
	}
	return nil
}

func (x *Api) GetExpansion() *Expansion {
	if x != nil {
		return x.Expansion
	}
	return nil
}

func (x *Api) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\bvalhalla\x1a\roptions.proto\x1a\n" +
	"trip.proto\x1a\x10directions.proto\x1a\n" +
	"info.proto\x1a\fstatus.proto\x1a\fmatrix.proto\x1a\x0fisochrone.proto\x1a\x0fexpansion.proto\"\xea\x02\n" +
	"\x03Api\x12+\n" +
	"\aoptions\x18\x01 \x01(\v2\x11.valhalla.OptionsR\aoptions\x12\"\n" +
	"\x04trip\x18\x02 \x01(\v2\x0e.valhalla.TripR\x04trip\x124\n" +
	"\n" +
	"directions\x18\x03 \x01(\v2\x14.valhalla.DirectionsR\n" +
	"directions\x12(\n" +
	"\x06status\x18\x04 \x01(\v2\x10.valhalla.StatusR\x06status\x12(\n" +
	"\x06matrix\x18\x05 \x01(\v2\x10.valhalla.MatrixR\x06matrix\x121\n" +
	"\tisochrone\x18\x06 \x01(\v2\x13.valhalla.IsochroneR\tisochrone\x121\n" +
	"\texpansion\x18\a \x01(\v2\x13.valhalla.ExpansionR\texpansion\x12\"\n" +
	"\x04info\x18\x14 \x01(\v2\x0e.valhalla.InfoR\x04infoB:H\x03Z6matching-engine/internal/adapter/valhalla/client/pb;pbP\x00P\x01P\x02P\x03P\x04P\x05P\x06P\ab\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_goTypes = []any{
	(*Api)(nil),        // 0: valhalla.Api
	(*Options)(nil),    // 1: valhalla.Options
	(*Trip)(nil),       // 2: valhalla.Trip
	(*Directions)(nil), // 3: valhalla.Directions
	(*Status)(nil),     // 4: valhalla.Status
	(*Matrix)(nil),     // 5: valhalla.Matrix
	(*Isochrone)(nil),  // 6: valhalla.Isochrone
	(*Expansion)(nil),  // 7: valhalla.Expansion
	(*Info)(nil),       // 8: valhalla.Info
}
var file_api_proto_depIdxs = []int32{
	1, // 0: valhalla.Api.options:type_name -> valhalla.Options
	2, // 1: valhalla.Api.trip:type_name -> valhalla.Trip
	3, // 2: valhalla.Api.directions:type_name -> valhalla.Directions
	4, // 3: valhalla.Api.status:type_name -> valhalla.Status
	5, // 4: valhalla.Api.matrix:type_name -> valhalla.Matrix
	6, // 5: valhalla.Api.isochrone:type_name -> valhalla.Isochrone
	7, // 6: valhalla.Api.expansion:type_name -> valhalla.Expansion
	8, // 7: valhalla.Api.info:type_name -> valhalla.Info
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_options_proto_init()
	file_trip_proto_init()
	file_directions_proto_init()
	file_info_proto_init()
	file_status_proto_init()
	file_matrix_proto_init()
	file_isochrone_proto_init()
	file_expansion_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
