// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: expansion.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Expansion_EdgeStatus int32

const (
	Expansion_connected Expansion_EdgeStatus = 0
	Expansion_settled   Expansion_EdgeStatus = 1
	Expansion_reached   Expansion_EdgeStatus = 2
)

// Enum value maps for Expansion_EdgeStatus.
var (
	Expansion_EdgeStatus_name = map[int32]string{
		0: "connected",
		1: "settled",
		2: "reached",
	}
	Expansion_EdgeStatus_value = map[string]int32{
		"connected": 0,
		"settled":   1,
		"reached":   2,
	}
)

func (x Expansion_EdgeStatus) Enum() *Expansion_EdgeStatus {
	p := new(Expansion_EdgeStatus)
	*p = x
	return p
}

func (x Expansion_EdgeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Expansion_EdgeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_expansion_proto_enumTypes[0].Descriptor()
}

func (Expansion_EdgeStatus) Type() protoreflect.EnumType {
	return &file_expansion_proto_enumTypes[0]
}

func (x Expansion_EdgeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Expansion_EdgeStatus.Descriptor instead.
func (Expansion_EdgeStatus) EnumDescriptor() ([]byte, []int) {
	return file_expansion_proto_rawDescGZIP(), []int{0, 0}
}

type Expansion_ExpansionType int32

const (
	Expansion_forward Expansion_ExpansionType = 0
	Expansion_reverse Expansion_ExpansionType = 1
)

// Enum value maps for Expansion_ExpansionType.
var (
	Expansion_ExpansionType_name = map[int32]string{
		0: "forward",
		1: "reverse",
	}
	Expansion_ExpansionType_value = map[string]int32{
		"forward": 0,
		"reverse": 1,
	}
)

func (x Expansion_ExpansionType) Enum() *Expansion_ExpansionType {
	p := new(Expansion_ExpansionType)
	*p = x
	return p
}

func (x Expansion_ExpansionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Expansion_ExpansionType) Descriptor() protoreflect.EnumDescriptor {
	return file_expansion_proto_enumTypes[1].Descriptor()
}

func (Expansion_ExpansionType) Type() protoreflect.EnumType {
	return &file_expansion_proto_enumTypes[1]
}

func (x Expansion_ExpansionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Expansion_ExpansionType.Descriptor instead.
func (Expansion_ExpansionType) EnumDescriptor() ([]byte, []int) {
	return file_expansion_proto_rawDescGZIP(), []int{0, 1}
}

type Expansion struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Costs         []uint32                  `protobuf:"varint,1,rep,packed,name=costs,proto3" json:"costs,omitempty"`
	Durations     []uint32                  `protobuf:"varint,2,rep,packed,name=durations,proto3" json:"durations,omitempty"`
	Distances     []uint32                  `protobuf:"varint,3,rep,packed,name=distances,proto3" json:"distances,omitempty"`
	EdgeStatus    []Expansion_EdgeStatus    `protobuf:"varint,4,rep,packed,name=edge_status,json=edgeStatus,proto3,enum=valhalla.Expansion_EdgeStatus" json:"edge_status,omitempty"`
	EdgeId        []uint32                  `protobuf:"varint,5,rep,packed,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	PredEdgeId    []uint32                  `protobuf:"varint,6,rep,packed,name=pred_edge_id,json=predEdgeId,proto3" json:"pred_edge_id,omitempty"`
	ExpansionType []Expansion_ExpansionType `protobuf:"varint,8,rep,packed,name=expansion_type,json=expansionType,proto3,enum=valhalla.Expansion_ExpansionType" json:"expansion_type,omitempty"`
	Geometries    []*Expansion_Geometry     `protobuf:"bytes,7,rep,name=geometries,proto3" json:"geometries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expansion) Reset() {
	*x = Expansion{}
	mi := &file_expansion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expansion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expansion) ProtoMessage() {}

func (x *Expansion) ProtoReflect() protoreflect.Message {
	mi := &file_expansion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expansion.ProtoReflect.Descriptor instead.
func (*Expansion) Descriptor() ([]byte, []int) {
	return file_expansion_proto_rawDescGZIP(), []int{0}
}

func (x *Expansion) GetCosts() []uint32 {
	if x != nil {
		return x.Costs
	}
	return nil
}

func (x *Expansion) GetDurations() []uint32 {
	if x != nil {
		return x.Durations
	}
	return nil
}

func (x *Expansion) GetDistances() []uint32 {
	if x != nil {
		return x.Distances
	}
	return nil
}

func (x *Expansion) GetEdgeStatus() []Expansion_EdgeStatus {
	if x != nil {
		return x.EdgeStatus
	}
	return nil
}

func (x *Expansion) GetEdgeId() []uint32 {
	if x != nil {
		return x.EdgeId
	}
	return nil
}

func (x *Expansion) GetPredEdgeId() []uint32 {
	if x != nil {
		return x.PredEdgeId
	}
	return nil
}

func (x *Expansion) GetExpansionType() []Expansion_ExpansionType {
	if x != nil {
		return x.ExpansionType
	}
	return nil
}

func (x *Expansion) GetGeometries() []*Expansion_Geometry {
	if x != nil {
		return x.Geometries
	}
	return nil
}

type Expansion_Geometry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coords        []int32                `protobuf:"zigzag32,1,rep,packed,name=coords,proto3" json:"coords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expansion_Geometry) Reset() {
	*x = Expansion_Geometry{}
	mi := &file_expansion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expansion_Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expansion_Geometry) ProtoMessage() {}

func (x *Expansion_Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_expansion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expansion_Geometry.ProtoReflect.Descriptor instead.
func (*Expansion_Geometry) Descriptor() ([]byte, []int) {
	return file_expansion_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Expansion_Geometry) GetCoords() []int32 {
	if x != nil {
		return x.Coords
	}
	return nil
}

var File_expansion_proto protoreflect.FileDescriptor

const file_expansion_proto_rawDesc = "" +
	"\n" +
	"\x0fexpansion.proto\x12\bvalhalla\"\xff\x03\n" +
	"\tExpansion\x12\x18\n" +
	"\x05costs\x18\x01 \x03(\rB\x02\x10\x01R\x05costs\x12 \n" +
	"\tdurations\x18\x02 \x03(\rB\x02\x10\x01R\tdurations\x12 \n" +
	"\tdistances\x18\x03 \x03(\rB\x02\x10\x01R\tdistances\x12?\n" +
	"\vedge_status\x18\x04 \x03(\x0e2\x1e.valhalla.Expansion.EdgeStatusR\n" +
	"edgeStatus\x12\x1b\n" +
	"\aedge_id\x18\x05 \x03(\rB\x02\x10\x01R\x06edgeId\x12$\n" +
	"\fpred_edge_id\x18\x06 \x03(\rB\x02\x10\x01R\n" +
	"predEdgeId\x12H\n" +
	"\x0eexpansion_type\x18\b \x03(\x0e2!.valhalla.Expansion.ExpansionTypeR\rexpansionType\x12<\n" +
	"\n" +
	"geometries\x18\a \x03(\v2\x1c.valhalla.Expansion.GeometryR\n" +
	"geometries\x1a&\n" +
	"\bGeometry\x12\x1a\n" +
	"\x06coords\x18\x01 \x03(\x11B\x02\x10\x01R\x06coords\"5\n" +
	"\n" +
	"EdgeStatus\x12\r\n" +
	"\tconnected\x10\x00\x12\v\n" +
	"\asettled\x10\x01\x12\v\n" +
	"\areached\x10\x02\")\n" +
	"\rExpansionType\x12\v\n" +
	"\aforward\x10\x00\x12\v\n" +
	"\areverse\x10\x01BIH\x03ZEmatching-engine/internal/adapter/routing-engine/valhalla/client/pb;pbb\x06proto3"

var (
	file_expansion_proto_rawDescOnce sync.Once
	file_expansion_proto_rawDescData []byte
)

func file_expansion_proto_rawDescGZIP() []byte {
	file_expansion_proto_rawDescOnce.Do(func() {
		file_expansion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expansion_proto_rawDesc), len(file_expansion_proto_rawDesc)))
	})
	return file_expansion_proto_rawDescData
}

var file_expansion_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_expansion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_expansion_proto_goTypes = []any{
	(Expansion_EdgeStatus)(0),    // 0: valhalla.Expansion.EdgeStatus
	(Expansion_ExpansionType)(0), // 1: valhalla.Expansion.ExpansionType
	(*Expansion)(nil),            // 2: valhalla.Expansion
	(*Expansion_Geometry)(nil),   // 3: valhalla.Expansion.Geometry
}
var file_expansion_proto_depIdxs = []int32{
	0, // 0: valhalla.Expansion.edge_status:type_name -> valhalla.Expansion.EdgeStatus
	1, // 1: valhalla.Expansion.expansion_type:type_name -> valhalla.Expansion.ExpansionType
	3, // 2: valhalla.Expansion.geometries:type_name -> valhalla.Expansion.Geometry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_expansion_proto_init() }
func file_expansion_proto_init() {
	if File_expansion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expansion_proto_rawDesc), len(file_expansion_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expansion_proto_goTypes,
		DependencyIndexes: file_expansion_proto_depIdxs,
		EnumInfos:         file_expansion_proto_enumTypes,
		MessageInfos:      file_expansion_proto_msgTypes,
	}.Build()
	File_expansion_proto = out.File
	file_expansion_proto_goTypes = nil
	file_expansion_proto_depIdxs = nil
}
