// File contains definitions for side-loaded data-structures
//
// Because of the more distributed nature of this data
// compared to the previous protobuf structures used in Valhalla
// it is important to follow the protobuf schema evolution rules
// when modifying this file

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: incidents.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncidentsTile_Metadata_Type int32

const (
	IncidentsTile_Metadata_ACCIDENT         IncidentsTile_Metadata_Type = 0
	IncidentsTile_Metadata_CONGESTION       IncidentsTile_Metadata_Type = 1
	IncidentsTile_Metadata_CONSTRUCTION     IncidentsTile_Metadata_Type = 2
	IncidentsTile_Metadata_DISABLED_VEHICLE IncidentsTile_Metadata_Type = 3
	IncidentsTile_Metadata_LANE_RESTRICTION IncidentsTile_Metadata_Type = 4
	IncidentsTile_Metadata_MASS_TRANSIT     IncidentsTile_Metadata_Type = 5
	IncidentsTile_Metadata_MISCELLANEOUS    IncidentsTile_Metadata_Type = 6
	IncidentsTile_Metadata_OTHER_NEWS       IncidentsTile_Metadata_Type = 7
	IncidentsTile_Metadata_PLANNED_EVENT    IncidentsTile_Metadata_Type = 8
	IncidentsTile_Metadata_ROAD_CLOSURE     IncidentsTile_Metadata_Type = 9
	IncidentsTile_Metadata_ROAD_HAZARD      IncidentsTile_Metadata_Type = 10
	IncidentsTile_Metadata_WEATHER          IncidentsTile_Metadata_Type = 11
)

// Enum value maps for IncidentsTile_Metadata_Type.
var (
	IncidentsTile_Metadata_Type_name = map[int32]string{
		0:  "ACCIDENT",
		1:  "CONGESTION",
		2:  "CONSTRUCTION",
		3:  "DISABLED_VEHICLE",
		4:  "LANE_RESTRICTION",
		5:  "MASS_TRANSIT",
		6:  "MISCELLANEOUS",
		7:  "OTHER_NEWS",
		8:  "PLANNED_EVENT",
		9:  "ROAD_CLOSURE",
		10: "ROAD_HAZARD",
		11: "WEATHER",
	}
	IncidentsTile_Metadata_Type_value = map[string]int32{
		"ACCIDENT":         0,
		"CONGESTION":       1,
		"CONSTRUCTION":     2,
		"DISABLED_VEHICLE": 3,
		"LANE_RESTRICTION": 4,
		"MASS_TRANSIT":     5,
		"MISCELLANEOUS":    6,
		"OTHER_NEWS":       7,
		"PLANNED_EVENT":    8,
		"ROAD_CLOSURE":     9,
		"ROAD_HAZARD":      10,
		"WEATHER":          11,
	}
)

func (x IncidentsTile_Metadata_Type) Enum() *IncidentsTile_Metadata_Type {
	p := new(IncidentsTile_Metadata_Type)
	*p = x
	return p
}

func (x IncidentsTile_Metadata_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentsTile_Metadata_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_incidents_proto_enumTypes[0].Descriptor()
}

func (IncidentsTile_Metadata_Type) Type() protoreflect.EnumType {
	return &file_incidents_proto_enumTypes[0]
}

func (x IncidentsTile_Metadata_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentsTile_Metadata_Type.Descriptor instead.
func (IncidentsTile_Metadata_Type) EnumDescriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{0, 1, 0}
}

type IncidentsTile_Metadata_Impact int32

const (
	IncidentsTile_Metadata_UNKNOWN  IncidentsTile_Metadata_Impact = 0
	IncidentsTile_Metadata_CRITICAL IncidentsTile_Metadata_Impact = 1
	IncidentsTile_Metadata_MAJOR    IncidentsTile_Metadata_Impact = 2
	IncidentsTile_Metadata_MINOR    IncidentsTile_Metadata_Impact = 3
	IncidentsTile_Metadata_LOW      IncidentsTile_Metadata_Impact = 4
)

// Enum value maps for IncidentsTile_Metadata_Impact.
var (
	IncidentsTile_Metadata_Impact_name = map[int32]string{
		0: "UNKNOWN",
		1: "CRITICAL",
		2: "MAJOR",
		3: "MINOR",
		4: "LOW",
	}
	IncidentsTile_Metadata_Impact_value = map[string]int32{
		"UNKNOWN":  0,
		"CRITICAL": 1,
		"MAJOR":    2,
		"MINOR":    3,
		"LOW":      4,
	}
)

func (x IncidentsTile_Metadata_Impact) Enum() *IncidentsTile_Metadata_Impact {
	p := new(IncidentsTile_Metadata_Impact)
	*p = x
	return p
}

func (x IncidentsTile_Metadata_Impact) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentsTile_Metadata_Impact) Descriptor() protoreflect.EnumDescriptor {
	return file_incidents_proto_enumTypes[1].Descriptor()
}

func (IncidentsTile_Metadata_Impact) Type() protoreflect.EnumType {
	return &file_incidents_proto_enumTypes[1]
}

func (x IncidentsTile_Metadata_Impact) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentsTile_Metadata_Impact.Descriptor instead.
func (IncidentsTile_Metadata_Impact) EnumDescriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{0, 1, 1}
}

type IncidentsTile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sorted list of edge_ids describing what incidents are attached to an edge_id
	Locations []*IncidentsTile_Location `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	// Look at `incident_locations` to find how to index this array
	Metadata      []*IncidentsTile_Metadata `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncidentsTile) Reset() {
	*x = IncidentsTile{}
	mi := &file_incidents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentsTile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentsTile) ProtoMessage() {}

func (x *IncidentsTile) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentsTile.ProtoReflect.Descriptor instead.
func (*IncidentsTile) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{0}
}

func (x *IncidentsTile) GetLocations() []*IncidentsTile_Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *IncidentsTile) GetMetadata() []*IncidentsTile_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Links a portion of an edge to incident metadata
type IncidentsTile_Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeIndex     uint32                 `protobuf:"varint,1,opt,name=edge_index,json=edgeIndex,proto3" json:"edge_index,omitempty"`
	StartOffset   float32                `protobuf:"fixed32,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     float32                `protobuf:"fixed32,3,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	MetadataIndex uint32                 `protobuf:"varint,4,opt,name=metadata_index,json=metadataIndex,proto3" json:"metadata_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncidentsTile_Location) Reset() {
	*x = IncidentsTile_Location{}
	mi := &file_incidents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentsTile_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentsTile_Location) ProtoMessage() {}

func (x *IncidentsTile_Location) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentsTile_Location.ProtoReflect.Descriptor instead.
func (*IncidentsTile_Location) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IncidentsTile_Location) GetEdgeIndex() uint32 {
	if x != nil {
		return x.EdgeIndex
	}
	return 0
}

func (x *IncidentsTile_Location) GetStartOffset() float32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *IncidentsTile_Location) GetEndOffset() float32 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *IncidentsTile_Location) GetMetadataIndex() uint32 {
	if x != nil {
		return x.MetadataIndex
	}
	return 0
}

// A single incident is described by this
// TODO This is not yet finalized
type IncidentsTile_Metadata struct {
	state        protoimpl.MessageState             `protogen:"open.v1"`
	Type         IncidentsTile_Metadata_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=valhalla.IncidentsTile_Metadata_Type" json:"type,omitempty"`
	AlertcCodes  []uint32                           `protobuf:"varint,2,rep,packed,name=alertc_codes,json=alertcCodes,proto3" json:"alertc_codes,omitempty"`
	Description        string                             `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SubType            string                             `protobuf:"bytes,4,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`
	SubTypeDescription string                             `protobuf:"bytes,5,opt,name=sub_type_description,json=subTypeDescription,proto3" json:"sub_type_description,omitempty"`
	StartTime          uint64                             `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime      uint64                             `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Impact       IncidentsTile_Metadata_Impact      `protobuf:"varint,9,opt,name=impact,proto3,enum=valhalla.IncidentsTile_Metadata_Impact" json:"impact,omitempty"`
	RoadClosed   bool                               `protobuf:"varint,10,opt,name=road_closed,json=roadClosed,proto3" json:"road_closed,omitempty"`
	Congestion   *IncidentsTile_Metadata_Congestion `protobuf:"bytes,11,opt,name=congestion,proto3" json:"congestion,omitempty"`
	LanesBlocked []string                           `protobuf:"bytes,12,rep,name=lanes_blocked,json=lanesBlocked,proto3" json:"lanes_blocked,omitempty"`
	CreationTime       uint64                             `protobuf:"varint,13,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	LongDescription    string                             `protobuf:"bytes,14,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	ClearLanes         string                             `protobuf:"bytes,15,opt,name=clear_lanes,json=clearLanes,proto3" json:"clear_lanes,omitempty"`
	NumLanesBlocked    uint64                             `protobuf:"varint,16,opt,name=num_lanes_blocked,json=numLanesBlocked,proto3" json:"num_lanes_blocked,omitempty"`
	Length             uint32                             `protobuf:"varint,17,opt,name=length,proto3" json:"length,omitempty"` // Length of incident as matched to road graph
	// IncidentMetadata id
	Id uint64 `protobuf:"varint,128,opt,name=id,proto3" json:"id,omitempty"`
	// Country code (2 & 3 char codes)
	Iso_3166_1Alpha2 string `protobuf:"bytes,129,opt,name=iso_3166_1_alpha2,json=iso31661Alpha2,proto3" json:"iso_3166_1_alpha2,omitempty"`
	Iso_3166_1Alpha3 string `protobuf:"bytes,130,opt,name=iso_3166_1_alpha3,json=iso31661Alpha3,proto3" json:"iso_3166_1_alpha3,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IncidentsTile_Metadata) Reset() {
	*x = IncidentsTile_Metadata{}
	mi := &file_incidents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentsTile_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentsTile_Metadata) ProtoMessage() {}

func (x *IncidentsTile_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentsTile_Metadata.ProtoReflect.Descriptor instead.
func (*IncidentsTile_Metadata) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{0, 1}
}

func (x *IncidentsTile_Metadata) GetType() IncidentsTile_Metadata_Type {
	if x != nil {
		return x.Type
	}
	return IncidentsTile_Metadata_ACCIDENT
}

func (x *IncidentsTile_Metadata) GetAlertcCodes() []uint32 {
	if x != nil {
		return x.AlertcCodes
	}
	return nil
}

func (x *IncidentsTile_Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IncidentsTile_Metadata) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *IncidentsTile_Metadata) GetSubTypeDescription() string {
	if x != nil {
		return x.SubTypeDescription
	}
	return ""
}

func (x *IncidentsTile_Metadata) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *IncidentsTile_Metadata) GetEndTime() uint64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *IncidentsTile_Metadata) GetImpact() IncidentsTile_Metadata_Impact {
	if x != nil {
		return x.Impact
	}
	return IncidentsTile_Metadata_UNKNOWN
}

func (x *IncidentsTile_Metadata) GetRoadClosed() bool {
	if x != nil {
		return x.RoadClosed
	}
	return false
}

func (x *IncidentsTile_Metadata) GetCongestion() *IncidentsTile_Metadata_Congestion {
	if x != nil {
		return x.Congestion
	}
	return nil
}

func (x *IncidentsTile_Metadata) GetLanesBlocked() []string {
	if x != nil {
		return x.LanesBlocked
	}
	return nil
}

func (x *IncidentsTile_Metadata) GetCreationTime() uint64 {
	if x != nil {
		return x.CreationTime
	}
	return 0
}

func (x *IncidentsTile_Metadata) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *IncidentsTile_Metadata) GetClearLanes() string {
	if x != nil {
		return x.ClearLanes
	}
	return ""
}

func (x *IncidentsTile_Metadata) GetNumLanesBlocked() uint64 {
	if x != nil {
		return x.NumLanesBlocked
	}
	return 0
}

func (x *IncidentsTile_Metadata) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *IncidentsTile_Metadata) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncidentsTile_Metadata) GetIso_3166_1Alpha2() string {
	if x != nil {
		return x.Iso_3166_1Alpha2
	}
	return ""
}

func (x *IncidentsTile_Metadata) GetIso_3166_1Alpha3() string {
	if x != nil {
		return x.Iso_3166_1Alpha3
	}
	return ""
}

type IncidentsTile_Metadata_Congestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncidentsTile_Metadata_Congestion) Reset() {
	*x = IncidentsTile_Metadata_Congestion{}
	mi := &file_incidents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentsTile_Metadata_Congestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentsTile_Metadata_Congestion) ProtoMessage() {}

func (x *IncidentsTile_Metadata_Congestion) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentsTile_Metadata_Congestion.ProtoReflect.Descriptor instead.
func (*IncidentsTile_Metadata_Congestion) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *IncidentsTile_Metadata_Congestion) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_incidents_proto protoreflect.FileDescriptor

const file_incidents_proto_rawDesc = "" +
	"\n" +
	"\x0fincidents.proto\x12\bvalhalla\"\xed\n" +
	"\n" +
	"\rIncidentsTile\x12>\n" +
	"\tlocations\x18\x01 \x03(\v2 .valhalla.IncidentsTile.LocationR\tlocations\x12<\n" +
	"\bmetadata\x18\x02 \x03(\v2 .valhalla.IncidentsTile.MetadataR\bmetadata\x1a\x92\x01\n" +
	"\bLocation\x12\x1d\n" +
	"\n" +
	"edge_index\x18\x01 \x01(\rR\tedgeIndex\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x02R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x03 \x01(\x02R\tendOffset\x12%\n" +
	"\x0emetadata_index\x18\x04 \x01(\rR\rmetadataIndex\x1a\xc8\b\n" +
	"\bMetadata\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.valhalla.IncidentsTile.Metadata.TypeR\x04type\x12!\n" +
	"\falertc_codes\x18\x02 \x03(\rR\valertcCodes\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bsub_type\x18\x04 \x01(\tR\asubType\x120\n" +
	"\x14sub_type_description\x18\x05 \x01(\tR\x12subTypeDescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x04R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x04R\aendTime\x12?\n" +
	"\x06impact\x18\t \x01(\x0e2'.valhalla.IncidentsTile.Metadata.ImpactR\x06impact\x12\x1f\n" +
	"\vroad_closed\x18\n" +
	" \x01(\bR\n" +
	"roadClosed\x12K\n" +
	"\n" +
	"congestion\x18\v \x01(\v2+.valhalla.IncidentsTile.Metadata.CongestionR\n" +
	"congestion\x12#\n" +
	"\rlanes_blocked\x18\f \x03(\tR\flanesBlocked\x12#\n" +
	"\rcreation_time\x18\r \x01(\x04R\fcreationTime\x12)\n" +
	"\x10long_description\x18\x0e \x01(\tR\x0flongDescription\x12\x1f\n" +
	"\vclear_lanes\x18\x0f \x01(\tR\n" +
	"clearLanes\x12*\n" +
	"\x11num_lanes_blocked\x18\x10 \x01(\x04R\x0fnumLanesBlocked\x12\x16\n" +
	"\x06length\x18\x11 \x01(\rR\x06length\x12\x0f\n" +
	"\x02id\x18\x80\x01 \x01(\x04R\x02id\x12*\n" +
	"\x11iso_3166_1_alpha2\x18\x81\x01 \x01(\tR\x0eiso31661Alpha2\x12*\n" +
	"\x11iso_3166_1_alpha3\x18\x82\x01 \x01(\tR\x0eiso31661Alpha3\x1a\"\n" +
	"\n" +
	"Congestion\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\"\xda\x01\n" +
	"\x04Type\x12\f\n" +
	"\bACCIDENT\x10\x00\x12\x0e\n" +
	"\n" +
	"CONGESTION\x10\x01\x12\x10\n" +
	"\fCONSTRUCTION\x10\x02\x12\x14\n" +
	"\x10DISABLED_VEHICLE\x10\x03\x12\x14\n" +
	"\x10LANE_RESTRICTION\x10\x04\x12\x10\n" +
	"\fMASS_TRANSIT\x10\x05\x12\x11\n" +
	"\rMISCELLANEOUS\x10\x06\x12\x0e\n" +
	"\n" +
	"OTHER_NEWS\x10\a\x12\x11\n" +
	"\rPLANNED_EVENT\x10\b\x12\x10\n" +
	"\fROAD_CLOSURE\x10\t\x12\x0f\n" +
	"\vROAD_HAZARD\x10\n" +
	"\x12\v\n" +
	"\aWEATHER\x10\v\"B\n" +
	"\x06Impact\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bCRITICAL\x10\x01\x12\t\n" +
	"\x05MAJOR\x10\x02\x12\t\n" +
	"\x05MINOR\x10\x03\x12\a\n" +
	"\x03LOW\x10\x04BIH\x03ZEmatching-engine/internal/adapter/routing-engine/valhalla/client/pb;pbb\x06proto3"

var (
	file_incidents_proto_rawDescOnce sync.Once
	file_incidents_proto_rawDescData []byte
)

func file_incidents_proto_rawDescGZIP() []byte {
	file_incidents_proto_rawDescOnce.Do(func() {
		file_incidents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incidents_proto_rawDesc), len(file_incidents_proto_rawDesc)))
	})
	return file_incidents_proto_rawDescData
}

var file_incidents_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_incidents_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_incidents_proto_goTypes = []any{
	(IncidentsTile_Metadata_Type)(0),          // 0: valhalla.IncidentsTile.Metadata.Type
	(IncidentsTile_Metadata_Impact)(0),        // 1: valhalla.IncidentsTile.Metadata.Impact
	(*IncidentsTile)(nil),                     // 2: valhalla.IncidentsTile
	(*IncidentsTile_Location)(nil),            // 3: valhalla.IncidentsTile.Location
	(*IncidentsTile_Metadata)(nil),            // 4: valhalla.IncidentsTile.Metadata
	(*IncidentsTile_Metadata_Congestion)(nil), // 5: valhalla.IncidentsTile.Metadata.Congestion
}
var file_incidents_proto_depIdxs = []int32{
	3, // 0: valhalla.IncidentsTile.locations:type_name -> valhalla.IncidentsTile.Location
	4, // 1: valhalla.IncidentsTile.metadata:type_name -> valhalla.IncidentsTile.Metadata
	0, // 2: valhalla.IncidentsTile.Metadata.type:type_name -> valhalla.IncidentsTile.Metadata.Type
	1, // 3: valhalla.IncidentsTile.Metadata.impact:type_name -> valhalla.IncidentsTile.Metadata.Impact
	5, // 4: valhalla.IncidentsTile.Metadata.congestion:type_name -> valhalla.IncidentsTile.Metadata.Congestion
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_incidents_proto_init() }
func file_incidents_proto_init() {
	if File_incidents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incidents_proto_rawDesc), len(file_incidents_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_incidents_proto_goTypes,
		DependencyIndexes: file_incidents_proto_depIdxs,
		EnumInfos:         file_incidents_proto_enumTypes,
		MessageInfos:      file_incidents_proto_msgTypes,
	}.Build()
	File_incidents_proto = out.File
	file_incidents_proto_goTypes = nil
	file_incidents_proto_depIdxs = nil
}
