// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: matrix.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Matrix_Algorithm int32

const (
	Matrix_TimeDistanceMatrix    Matrix_Algorithm = 0
	Matrix_CostMatrix            Matrix_Algorithm = 1
	Matrix_TimeDistanceBSSMatrix Matrix_Algorithm = 2
)

// Enum value maps for Matrix_Algorithm.
var (
	Matrix_Algorithm_name = map[int32]string{
		0: "TimeDistanceMatrix",
		1: "CostMatrix",
		2: "TimeDistanceBSSMatrix",
	}
	Matrix_Algorithm_value = map[string]int32{
		"TimeDistanceMatrix":    0,
		"CostMatrix":            1,
		"TimeDistanceBSSMatrix": 2,
	}
)

func (x Matrix_Algorithm) Enum() *Matrix_Algorithm {
	p := new(Matrix_Algorithm)
	*p = x
	return p
}

func (x Matrix_Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Matrix_Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_matrix_proto_enumTypes[0].Descriptor()
}

func (Matrix_Algorithm) Type() protoreflect.EnumType {
	return &file_matrix_proto_enumTypes[0]
}

func (x Matrix_Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Matrix_Algorithm.Descriptor instead.
func (Matrix_Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_matrix_proto_rawDescGZIP(), []int{0, 0}
}

type Matrix struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Distances       []uint32               `protobuf:"varint,2,rep,packed,name=distances,proto3" json:"distances,omitempty"`
	Times           []float32              `protobuf:"fixed32,3,rep,packed,name=times,proto3" json:"times,omitempty"`
	FromIndices     []uint32               `protobuf:"varint,4,rep,packed,name=from_indices,json=fromIndices,proto3" json:"from_indices,omitempty"`
	ToIndices       []uint32               `protobuf:"varint,5,rep,packed,name=to_indices,json=toIndices,proto3" json:"to_indices,omitempty"`
	DateTimes []string         `protobuf:"bytes,6,rep,name=date_times,json=dateTimes,proto3" json:"date_times,omitempty"`
	Algorithm Matrix_Algorithm `protobuf:"varint,7,opt,name=algorithm,proto3,enum=valhalla.Matrix_Algorithm" json:"algorithm,omitempty"`
	Shapes    []string         `protobuf:"bytes,8,rep,name=shapes,proto3" json:"shapes,omitempty"`
	TimeZoneOffsets []string               `protobuf:"bytes,9,rep,name=time_zone_offsets,json=timeZoneOffsets,proto3" json:"time_zone_offsets,omitempty"`
	TimeZoneNames   []string               `protobuf:"bytes,10,rep,name=time_zone_names,json=timeZoneNames,proto3" json:"time_zone_names,omitempty"`
	SecondPass      []bool                 `protobuf:"varint,11,rep,packed,name=second_pass,json=secondPass,proto3" json:"second_pass,omitempty"`
	BeginHeading    []float32              `protobuf:"fixed32,12,rep,packed,name=begin_heading,json=beginHeading,proto3" json:"begin_heading,omitempty"`
	EndHeading      []float32              `protobuf:"fixed32,13,rep,packed,name=end_heading,json=endHeading,proto3" json:"end_heading,omitempty"`
	BeginLat        []float64              `protobuf:"fixed64,14,rep,packed,name=begin_lat,json=beginLat,proto3" json:"begin_lat,omitempty"`
	BeginLon        []float64              `protobuf:"fixed64,15,rep,packed,name=begin_lon,json=beginLon,proto3" json:"begin_lon,omitempty"`
	EndLat          []float64              `protobuf:"fixed64,16,rep,packed,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	EndLon          []float64              `protobuf:"fixed64,17,rep,packed,name=end_lon,json=endLon,proto3" json:"end_lon,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Matrix) Reset() {
	*x = Matrix{}
	mi := &file_matrix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix) ProtoMessage() {}

func (x *Matrix) ProtoReflect() protoreflect.Message {
	mi := &file_matrix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix.ProtoReflect.Descriptor instead.
func (*Matrix) Descriptor() ([]byte, []int) {
	return file_matrix_proto_rawDescGZIP(), []int{0}
}

func (x *Matrix) GetDistances() []uint32 {
	if x != nil {
		return x.Distances
	}
	return nil
}

func (x *Matrix) GetTimes() []float32 {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *Matrix) GetFromIndices() []uint32 {
	if x != nil {
		return x.FromIndices
	}
	return nil
}

func (x *Matrix) GetToIndices() []uint32 {
	if x != nil {
		return x.ToIndices
	}
	return nil
}

func (x *Matrix) GetDateTimes() []string {
	if x != nil {
		return x.DateTimes
	}
	return nil
}

func (x *Matrix) GetAlgorithm() Matrix_Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Matrix_TimeDistanceMatrix
}

func (x *Matrix) GetShapes() []string {
	if x != nil {
		return x.Shapes
	}
	return nil
}

func (x *Matrix) GetTimeZoneOffsets() []string {
	if x != nil {
		return x.TimeZoneOffsets
	}
	return nil
}

func (x *Matrix) GetTimeZoneNames() []string {
	if x != nil {
		return x.TimeZoneNames
	}
	return nil
}

func (x *Matrix) GetSecondPass() []bool {
	if x != nil {
		return x.SecondPass
	}
	return nil
}

func (x *Matrix) GetBeginHeading() []float32 {
	if x != nil {
		return x.BeginHeading
	}
	return nil
}

func (x *Matrix) GetEndHeading() []float32 {
	if x != nil {
		return x.EndHeading
	}
	return nil
}

func (x *Matrix) GetBeginLat() []float64 {
	if x != nil {
		return x.BeginLat
	}
	return nil
}

func (x *Matrix) GetBeginLon() []float64 {
	if x != nil {
		return x.BeginLon
	}
	return nil
}

func (x *Matrix) GetEndLat() []float64 {
	if x != nil {
		return x.EndLat
	}
	return nil
}

func (x *Matrix) GetEndLon() []float64 {
	if x != nil {
		return x.EndLon
	}
	return nil
}

var File_matrix_proto protoreflect.FileDescriptor

const file_matrix_proto_rawDesc = "" +
	"\n" +
	"\fmatrix.proto\x12\bvalhalla\x1a\fcommon.proto\"\xe6\x04\n" +
	"\x06Matrix\x12\x1c\n" +
	"\tdistances\x18\x02 \x03(\rR\tdistances\x12\x14\n" +
	"\x05times\x18\x03 \x03(\x02R\x05times\x12!\n" +
	"\ffrom_indices\x18\x04 \x03(\rR\vfromIndices\x12\x1d\n" +
	"\n" +
	"to_indices\x18\x05 \x03(\rR\ttoIndices\x12\x1d\n" +
	"\n" +
	"date_times\x18\x06 \x03(\tR\tdateTimes\x128\n" +
	"\talgorithm\x18\a \x01(\x0e2\x1a.valhalla.Matrix.AlgorithmR\talgorithm\x12\x16\n" +
	"\x06shapes\x18\b \x03(\tR\x06shapes\x12*\n" +
	"\x11time_zone_offsets\x18\t \x03(\tR\x0ftimeZoneOffsets\x12&\n" +
	"\x0ftime_zone_names\x18\n" +
	" \x03(\tR\rtimeZoneNames\x12\x1f\n" +
	"\vsecond_pass\x18\v \x03(\bR\n" +
	"secondPass\x12#\n" +
	"\rbegin_heading\x18\f \x03(\x02R\fbeginHeading\x12\x1f\n" +
	"\vend_heading\x18\r \x03(\x02R\n" +
	"endHeading\x12\x1b\n" +
	"\tbegin_lat\x18\x0e \x03(\x01R\bbeginLat\x12\x1b\n" +
	"\tbegin_lon\x18\x0f \x03(\x01R\bbeginLon\x12\x17\n" +
	"\aend_lat\x18\x10 \x03(\x01R\x06endLat\x12\x17\n" +
	"\aend_lon\x18\x11 \x03(\x01R\x06endLon\"N\n" +
	"\tAlgorithm\x12\x16\n" +
	"\x12TimeDistanceMatrix\x10\x00\x12\x0e\n" +
	"\n" +
	"CostMatrix\x10\x01\x12\x19\n" +
	"\x15TimeDistanceBSSMatrix\x10\x02BIH\x03ZEmatching-engine/internal/adapter/routing-engine/valhalla/client/pb;pbP\x00b\x06proto3"

var (
	file_matrix_proto_rawDescOnce sync.Once
	file_matrix_proto_rawDescData []byte
)

func file_matrix_proto_rawDescGZIP() []byte {
	file_matrix_proto_rawDescOnce.Do(func() {
		file_matrix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matrix_proto_rawDesc), len(file_matrix_proto_rawDesc)))
	})
	return file_matrix_proto_rawDescData
}

var file_matrix_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_matrix_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_matrix_proto_goTypes = []any{
	(Matrix_Algorithm)(0), // 0: valhalla.Matrix.Algorithm
	(*Matrix)(nil),        // 1: valhalla.Matrix
}
var file_matrix_proto_depIdxs = []int32{
	0, // 0: valhalla.Matrix.algorithm:type_name -> valhalla.Matrix.Algorithm
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_matrix_proto_init() }
func file_matrix_proto_init() {
	if File_matrix_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matrix_proto_rawDesc), len(file_matrix_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matrix_proto_goTypes,
		DependencyIndexes: file_matrix_proto_depIdxs,
		EnumInfos:         file_matrix_proto_enumTypes,
		MessageInfos:      file_matrix_proto_msgTypes,
	}.Build()
	File_matrix_proto = out.File
	file_matrix_proto_goTypes = nil
	file_matrix_proto_depIdxs = nil
}
